version: "3.9"

services:
  backend:
    build: ./backend
    container_name: wherehouse-backend
    # if later you make it a web server:
    # ports:
    #   - "8080:8080"

  frontend:
    build: ./frontend
    container_name: wherehouse-frontend
    ports:
      - "3000:80" # browser -> localhost:3000
    depends_on:
      - backend
